version: '3.7'
services:
  db:
    container_name: YOURCONTAINERNAME
    build:
      context: ./Docker/
      args:
        - USERNAME=$USERNAME
        - PASSWORD=$PASSWORD
        - SA_PASSWORD=$SA_PASSWORD
    environment:
      - SA_PASSWORD=${SA_PASSWORD}
      - ACCEPT_EULA=${ACCEPT_EULA}
    ports:
      - '1433:1433'